version: "3.8"

services:
  web1:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: web1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 10s
      timeout: 2s
      retries: 3

  web2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: web2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 10s
      timeout: 2s
      retries: 3

  web3:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: web3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 10s
      timeout: 2s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: balanceador
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx_balanceador.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web1
      - web2
      - web3
